In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('all_dec_data.csv')
df.drop(columns=['brand', 'cleaned_title'], inplace=True)

df.to_csv('all_dec_data_cleaned.csv', index=False)

/var/folders/67/wknnxysn29s5zc375pft99140000gn/T/ipykernel_86178/299797893.py:1: DtypeWarning: Columns (0: own_brand) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('all_dec_data.csv')

In [3]:
df = pd.read_csv('data/raw.csv')
df.head()

/var/folders/67/wknnxysn29s5zc375pft99140000gn/T/ipykernel_86883/1436705728.py:1: DtypeWarning: Columns (0: own_brand) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/raw.csv')

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
0,ASDA,4.75,19.8,kg,Tassimo Cadbury Hot Chocolate Pods x 8,20240413,drinks,False
1,ASDA,2.00,26.7,kg,Taylors of Harrogate Hot Lava Java Coffee Bags,20240413,drinks,False
2,ASDA,5.00,20.8,kg,Tassimo Limited Edition Cadbury Orange Hot Cho...,20240413,drinks,False
3,ASDA,3.50,15.4,kg,ASDA Extra Special Brazilian Ground Coffee,20240413,drinks,True
4,ASDA,3.50,15.4,kg,ASDA Extra Special Espresso Coffee Beans,20240413,drinks,True

In [4]:
df['category'].value_counts()

category
food_cupboard      26670
home               22396
health_products    21309
fresh_food         14837
drinks             13620
household           6672
frozen              3951
baby_products       3818
pets                3703
free-from           3682
bakery              2713
Name: count, dtype: int64

In [5]:
# Filter df by specified categories
categories_to_keep = ['bakery', 'drinks', 'food_cupboard', 'free-from', 'fresh_food', 'frozen']
df_filtered = df[df['category'].isin(categories_to_keep)]
df_filtered.head()

,supermarket,prices_(£),prices_unit_(£),unit,names,date,category,own_brand
0,ASDA,4.75,19.8,kg,Tassimo Cadbury Hot Chocolate Pods x 8,20240413,drinks,False
1,ASDA,2.00,26.7,kg,Taylors of Harrogate Hot Lava Java Coffee Bags,20240413,drinks,False
2,ASDA,5.00,20.8,kg,Tassimo Limited Edition Cadbury Orange Hot Cho...,20240413,drinks,False
3,ASDA,3.50,15.4,kg,ASDA Extra Special Brazilian Ground Coffee,20240413,drinks,True
4,ASDA,3.50,15.4,kg,ASDA Extra Special Espresso Coffee Beans,20240413,drinks,True

In [6]:
# Check the filtered dataframe statistics
print(f"Original dataframe shape: {df.shape}")
print(f"Filtered dataframe shape: {df_filtered.shape}")
print(f"\nCategory distribution in filtered dataframe:")
df_filtered['category'].value_counts()

Original dataframe shape: (123371, 8)
Filtered dataframe shape: (65473, 8)

Category distribution in filtered dataframe:

category
food_cupboard    26670
fresh_food       14837
drinks           13620
frozen            3951
free-from         3682
bakery            2713
Name: count, dtype: int64

In [7]:
df_filtered.to_csv('data/filtered.csv', index=False)